response = [
  " 脚踏实地 (jiǎo tà shí dì)
 literally means “to step on solid ground.” It means that, like Warren Buffet, you work hard, focus on the fundamentals, and proceed in a steady and stable fashion. It’s an extremely positive chengyu. Here’s an example : “现在我们要继续脚踏实地”   “xiànzài wǒmen yào jìxù jiǎotàshídì”   “Right now we need to continue staying grounded and pushing ahead”
",
  "九牛一毛 (jiǔ niú yì máo) literally means “9 cows and 1 strand of cow hair.” It indicates something that’s so small that it’s like one strand of cow hair among 9 cows. Here’s an example: “电子商务的盈利在中国整体商业环境中简直是九牛一毛.”   “diànzǐ shāngwù de yínglì zài zhōngguó zhěngtǐ shāngyè huánjìng zhōng jiǎnzhí shì jiǔniúyìmáo.”   “In the entire Chinese commercial environment, the profits from E-commerce are simply just a drop in the bucket.”  .",
  "一无所有 (yìwúsuǒyǒu) means to have absolutely nothing at all. It’s basically being penniless. Here’s an example: “他无家可归，一无所有”   “tā wújiākěguī， yìwúsuǒyǒu”   “He was homeless, and didn’t have a penny to his name”
",
  "一见钟情(yí jiàn zhōng qíng) means that something is free and easy. It can be used to describe someone’s personality, how someone behaves, or how a place makes people feel. For example: “这是一个自由自在的地方。”   “zhè shì yī gè zì yóu zì zai de dì fāng”   “This is a free and easy place” ",
  "莫名其妙 (mò míng qí miào) 莫名其妙 literally means that it’s hard to articulate the profoundness or mystery or something. It basically means that something is baffling. For example: “他说了几句莫名其妙的话。”   “tā shuì le jī gōu mò míng qí miào de huà”   “He said some mysterious words. ” ",
  "半途而废 (bàn tú ér fèi) means to start doing something, only to give up halfway. Literally, it means to walk half the road and give up. (Don’t do that with chengyu!) Here’s an example: “我不是半途而废的人”   “wǒ búshì bàntúérfèi de rén”   “I’m not someone who gives up halfway”",
  "抛砖引玉 (pāo zhuān yǐn yù) basically means you’re “just tossing an idea out there.” It literally means “to cast a brick to attract jade.” You’re basically saying, “this idea I’m tossing out there is garbage, but perhaps it will lead one of you to make a better contribution.” It’s a humble way to contribute to a conversation. Here’s an example: “我的建议还不够成熟，算是抛砖引玉吧 “   “wǒ de jiàn yì hái bú gòu chéng shú, suàn shì pāo zhuān yǐn yù ba “   “My suggestion is still half-baked — you could see it as just me tossing an idea out there“
",
  "豁然开朗 (huò rán kāi lǎng) has two meanings which are linked. The first meaning is the refreshing and liberating feeling you get when you see a beautiful, open area. Typically, immediately before this moment, the beautiful area is not visible and you might be feeling a little stuffy. Second, it’s also used for the feeling you get when you achieve an “aha” or “eureka!” moment. Here’s an example: “大学时期，乔尼开始有机会用Mac做设计，那是一种豁然开朗的体验“   “dàxué shíqí, qiáoní kāishǐ yǒujīhuì yòng Mac zuò shèjì, nàshì yīzhǒng huòránkāilǎng de tǐyàn”   “During college, Jony began to have opportunities to use a Mac to design, and that was a refreshing, eye-opening experience” ",
  "津津有味 (jīn jīn yǒu wèi) means to eat something deliciously. Also, it can be used for activities beyond just eating, as long as the person doing the activity finds it engaging. It’s not something that people typically use to describe themselves, but you can liberally use it on your friends as it has a positive tone. Here’s an expressive example: “津津有味地看报”   “jīnjīnyǒuwèi de kànbào”   “to devour the newspaper”  ",
  "理所当然 (lǐ suǒ dāng rán)sounds like “to go without saying” or “as a matter of course,” but literally means that “according to reason, it should be the case.” Here’s an example: “Some things which are obvious or natural in the course of a marriage…”   “。。。在婚姻中的一些～的事。。。”   “。。。zài hūnyīn zhōng de yīxiē ～de shì ",
  " 全力以赴 (quán lì yǐ fù) basically means to give it your all (literally “exert all your strength”) for a goal. It has a positive tone, and is somewhat formal but can still be used in everyday speech. It’s important to note that 全力以赴 is typically used for actions that haven’t finished yet, rather than actions that have already been completed. Here’s an example: “无论考生的笔试成绩如何，都要全力以赴准备面试”   “wúlùn kǎoshēng de bǐshì chéngjì rúhé ，dōuyào quánlìyǐfù zhǔnbèi miànshì”   “No matter how the student’s written test score is, he/she needs to give 100% to prepare for the interview”  ",
  "心血来潮 (xīn xuè lái cháo) basically means “spur of the moment” or “on a whim.” Literally, it evokes the image of blood rushing to your heart (of course in English we’d say head). It’s a perfect chengyu for when you’re telling a story a friend. For example: “某日他们心血来潮，决定比拼一下各自的脚法“   “mǒu rì tāmen xīnxuèláicháo,juédìng bǐpīn yíxià gèzì de jiǎofǎ”   “One day, on a spur of the moment, they decided to compare and compete to see whose footwork was best”  ",
  "乱七八糟 (luàn qī bā zāo) means that something is a total mess. You can use it to describe tangible things like messy rooms, or more abstract things, like a messed up life. For example: 是谁弄得乱七八糟的？   “shì shéi nòng de luàn qī bā zāo de?”   “who made this mess?” ",
  "不可思议 (bù kě sī yì)  means that something is noteworthy or amazing in an unexpected way. It can be used for things which are really amazing (eg. magic or larger phenomena) but also for unexpected, everyday occurrences. For example: “真是不可思议，我的名字跟你一样！”   “zhēn shi bù kĕ sī yì wŏ de míng zi gēn nĭ yī yàng”   “It’s incredible, I have the same name as you!” "
]

module.exports = (robot) ->
  robot.respond /(chinese idiom).*/i, (msg) ->
    msg.send msg.random response
